import Head from "next/head";
import Banner from "@/components/banner/banner";
import Navbar from "@/components/navbar/navbar";
import styles from "@/styles/Home.module.css";
import CardsSection from "@/components/cards-section/cards-section";

export default function Home() {
  const disneyVideos = [
    {
      imgUrl: "/static/clifford.webp",
    },
    {
      imgUrl: "/static/clifford.webp",
    },
    {
      imgUrl: "/static/clifford.webp",
    },
    {
      imgUrl: "/static/clifford.webp",
    },
    {
      imgUrl: "/static/clifford.webp",
    },
    {
      imgUrl: "/static/clifford.webp",
    },
  ];
  return (
    <>
      <Head>
        <title>Netflix</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar userName="ismail" />
      <Banner
        imgUrl="/static/clifford.webp"
        subTitle="cute dog"
        title="clifford the big red dog"
      />
      <div className={styles.sectionWrapper}>
        <CardsSection title="DC" videos={disneyVideos} size="large" />
        <CardsSection title="DC" videos={disneyVideos} size="medium" />
        <CardsSection title="DC" videos={disneyVideos} size="small" />
      </div>
    </>
  );
}
