import Head from "next/head";
import Banner from "@/components/banner/banner";
import styles from "@/styles/Home.module.css";

export default function Home() {
  return (
    <>
      <Head>
        <title>Netflix</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <h1>Netflix</h1>
      <Banner
        imgUrl="/static/clifford.webp"
        subTitle="cute dog"
        title="clifford the big red dog"
      />
    </>
  );
}
